- name: AWS VPN Site to Site creation
  hosts: paloalto-vm
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Create tunnel interface for AWS tunnel.1 169.xxx.xxx.1/30 mtu 1427
    panos_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      if_name: tunnel.1
      ip: 169.xxx.xxx.1/30
      vr_name: 'default'
      zone_name: 'AWS_IPSec_Zones'
      mtu: '1427'
      comment: 'IPSec connection to AWS - BGP Tunnel#1'
      management_profile: 'ping-only'
      commit: 'False'

  - name: Create tunnel interface for AWS tunnel.2 169.xxx.xxx.5/30 mtu 1427
    panos_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      if_name: tunnel.2
      ip: 169.xxx.xxx.5/30
      vr_name: 'default'
      zone_name: 'AWS_IPSec_Zones'
      mtu: '1427'
      comment: 'IPSec connection to AWS - BGP Tunnel#2'
      management_profile: 'ping-only'
      commit: 'False'

  - name: Add IKE crypto config to the firewall
    panos_ike_crypto_profile:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'AWS-IKE-Crypto'
      dhgroup: 'group2'
      authentication: 'sha1'
      encryption: 'aes-128-cbc'
      lifetime_sec: '28800'
      commit: 'False'

  - name: Add IPSec crypto config to the firewall
    panos_ipsec_profile:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'AWS-IPSEC-CRYPTO'
      esp_encryption: 'aes-128-cbc'
      esp_authentication: 'sha1'
      dhgroup: 'group2'
      lifetime_seconds: '3600'
      commit: 'False'

  - name: Add IKE gateway config - Gateway#1
    panos_ike_gateway:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'AWS-IKEGW01'
      version: 'ikev1'
      interface: 'ethernet1/1'
      local_ip_address: '111.xxx.xxx.18/24'
      local_ip_address_type: 'ip'
      ikev1_crypto_profile: 'AWS-IKE-Crypto'
      ikev1_exchange_mode: 'main'
      peer_ip_value: '3.x.xx.xxx'
      pre_shared_key: 'PLEASECHANGEME-PRESHAREDKEY'
      enable_passive_mode: 'False'
      enable_dead_peer_detection: 'True'
      dead_peer_detection_interval: '10' 
      dead_peer_detection_retry: '3'
      commit: False

  - name: Add IKE gateway config - Gateway#2
    panos_ike_gateway:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'AWS-IKEGW02'
      version: 'ikev1'
      interface: 'ethernet1/1'
      local_ip_address: '111.xxx.xxx.18/24'
      local_ip_address_type: 'ip'
      ikev1_crypto_profile: 'AWS-IKE-Crypto'
      ikev1_exchange_mode: 'main'
      peer_ip_value: '52.xx.xx.xxx'
      pre_shared_key: 'PLEASECHANGEME-PRESHAREDKEY'
      enable_passive_mode: 'False'
      enable_dead_peer_detection: 'True'
      dead_peer_detection_interval: '10'
      dead_peer_detection_retry: '3'
      commit: False

  - name: Add IPSec tunnel to IKE gateway profile - Tunnel#1
    panos_ipsec_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      type: 'auto-key'
      name: 'ID-JKT-AWS-Tunnel01'
      tunnel_interface: 'tunnel.1'
      ike_gtw_name: 'AWS-IKEGW01'
      ipsec_profile: 'AWS-IPSEC-CRYPTO'
      commit: 'False'

  - name: Add IPSec tunnel to IKE gateway profile - Tunnel#2
    panos_ipsec_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      type: 'auto-key'
      name: 'ID-JKT-AWS-Tunnel02'
      tunnel_interface: 'tunnel.2'
      ike_gtw_name: 'AWS-IKEGW02'
      ipsec_profile: 'AWS-IPSEC-CRYPTO'
      commit: 'False'