- name: Firewall commit
  hosts: paloalto-vm
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Commit pending firewall changes
    panos_commit:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'